# Generated by Django 3.0.14 on 2021-06-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0003_project_operator_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of writting'),
        ),
        migrations.AddField(
            model_name='book',
            name='joner',
            field=models.CharField(blank=True, choices=[('HORROR', 'HORROR'), ('FANTASY', 'FANTASY'), ('FACTUAL', 'FACTUAL'), ('Mystery', 'Mystery'), ('Historical Fiction', 'Historical Fiction'), ('Literary Fiction', 'Literary Fiction'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Short Stories', 'Short Stories'), ('nse and Thrillers', 'nse and Thrillers'), ('Biographies', 'Biographies')], max_length=20, null=True, verbose_name='Joner of book'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
    ]
