# Generated by Django 3.0.14 on 2021-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0005_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='joner',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='read',
        ),
        migrations.AddField(
            model_name='shelf',
            name='jouner',
            field=models.CharField(blank=True, choices=[('HORROR', 'HORROR'), ('FANTASY', 'FANTASY'), ('FACTUAL', 'FACTUAL'), ('Mystery', 'Mystery'), ('Historical Fiction', 'Historical Fiction'), ('Literary Fiction', 'Literary Fiction'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Short Stories', 'Short Stories'), ('nse and Thrillers', 'nse and Thrillers'), ('Biographies', 'Biographies')], max_length=50, null=True, verbose_name='Jouner'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='locked',
            field=models.BooleanField(default=True, verbose_name='Is locked'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of books'),
        ),
    ]
