# Generated by Django 3.0.14 on 2021-06-20 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_project', '0006_auto_20210620_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner of shelf'),
        ),
    ]
