# Generated by Django 3.0.14 on 2021-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0007_shelf_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create at'),
        ),
    ]
